export const defaultSocialData = {
    "Daniel":{
        platforms:["Facebook","TikTok"]
    },
    "Kelly":{
        platforms:["Facebook"]
    },
    "April":{
        platforms:["Facebook","Instagram"]
    },
    "Viel":{
        platforms:[]
    },
    "Arianne":{
        platforms:["Instagram","TikTok"]
    },
    "Craig":{
        platforms:["Facebook","X"]
    },
    "Regine":{
        platforms:["Facebook"]
    },
    "Nylvia":{
        platforms:["Facebook","TikTok"]
    },
    "Phoeboy":{
        platforms:["X"]
    },
    "Steven":{
        platforms:["Facebook"]
    }
};
